### PR TITLE
[Quest Enhancement] Spicing up the Quest Line and make Quest more Interesting

### PR DESCRIPTION
**Pull request by bioastroiner**
The Quests in questlines can use more descriptions and have some Interesting Rewards, be more unique and rewarding!
Put it to say, be More different and special, Ultimately being more fun to play with! I always had more Fun playing with themed packs such as Omnifactory and GTNH, FTB packs... than the ones with more generic quest lines (it's better to have none at all than have a boring one! like Impact and AoE!), apart from their progression Structure , Quests were really a Big Part to make a themed Pack more interesting! Quests really stand out to show what the pack can offer from little aspect and major ones, and since gregicality is new, It would be lot more interesting to Player to see what this can offer! therefore...

I added two new Quests to this pack in the steam age explaining roughly how mining works, I'll add more. Also since discriptions sometimes get a little bit too long, I put a color scheme to the text to make it more readable, put that hint in an informative quest, allowing player to skip through the quests in no time! here some sceen from the new quests, I'll add more since it's really FUN!

image
image
image
image
image

### CODE REVIEW

**Comment by SpeeeDCraft** [comment]
Quests currently have two translations, into Russian and into English. You need to make a translation into two languages. Try to do the same through the localization file, which is located in /resources/contenttweaker/lang/en_eu. If the design is saved. Then it will be possible to add this system. P. s you do not need to translate it into Russian. I'll take care of it. Only for English.

**Comment by bioastroiner** [comment]
> 
> 
> Quests currently have two translations, into Russian and into English. You need to make a translation into two languages. Try to do the same through the localization file, which is located in /resources/contenttweaker/lang/en_eu. If the design is saved. Then it will be possible to add this system. P.s you do not need to translate it into Russian. I'll take care of it. Only for English.

That's great, I will migrate the current quests, then entirely make the new ones with translation keys.

**Comment by SpeeeDCraft** [comment]
> > Quests currently have two translations, into Russian and into English. You need to make a translation into two languages. Try to do the same through the localization file, which is located in /resources/contenttweaker/lang/en_eu. If the design is saved. Then it will be possible to add this system. P.s you do not need to translate it into Russian. I'll take care of it. Only for English.
> 
> That's great, I will migrate the current quests, then entirely make the new ones with translation keys.

its nice, and you can rename tfg(in translations keys) --> iim :D. It's more aesthetically pleasing

**Comment by bioastroiner** [comment]
> 
> 
> > > Quests currently have two translations, into Russian and into English. You need to make a translation into two languages. Try to do the same through the localization file, which is located in /resources/contenttweaker/lang/en_eu. If the design is saved. Then it will be possible to add this system. P.s you do not need to translate it into Russian. I'll take care of it. Only for English.
> > 
> > 
> > That's great, I will migrate the current quests, then entirely make the new ones with translation keys.
> 
> its nice, and you can rename tfg(in translations keys) --> iim :D. It's more aesthetically pleasing

oh so i gauss Quest were from terra firma greg, that explains the distilled water and some tfc quests, i reordered some of the steam and Primitive Age Quests, I don't think i will change the tfg prfix in localizations right now, but i will change it soon it shouldn't be hard.

**Comment by SpeeeDCraft** [comment]
Thank you for your hard work

**Comment by SpeeeDCraft** [comment]
As soon as the Pull Request is ready I will merge it with the main branch

**Pull request merged**
